### ISSUE TITLE
new bests deaths count as x2

### ISSUE THREAD

**Issue by Craanky** [eloh-mrow/death-tracker#1] opened 2024-02-04 19:45 UTC
Fix it pls

**Comment by eloh-mrow** [comment] 2024-02-04 20:15
i'm not having this issue? can you show a video of it happening on a level you haven't played before?

**Comment by Craanky** [comment] 2024-02-05 07:35
idk why it happened then, atleast it counted twice for me 
![image](https://github.com/eloh-mrow/death-tracker/assets/140118512/33c0147d-9b65-4381-b4ac-f6bed3252eab)

**Comment by eloh-mrow** [comment] 2024-02-05 22:36
@Craanky if you die at 77% twice it will count as you dying at 77% twice? I'm not sure what the issue is here. if you could post a video of it happening that would help a lot

**Comment by Craanky** [comment] 2024-02-09 12:35
> @Craanky if you die at 77% twice it will count as you dying at 77% twice? I'm not sure what the issue is here. if you could post a video of it happening that would help a lot

idk how to replicate it myself, for me it counted sometimes twice at least (pls just believe me i only died once on 77% but it counted as 2) it also counted 78% as 12 times as an example (i think i died "only" 6 times there) 
![Uploading image.png…]()

**Comment by eloh-mrow** [comment] 2024-02-09 16:40
@Craanky its not that i dont believe you, i just cant get it to happen for me. if i cant get it to happen theres no way that i can fix it

**Comment by eloh-mrow** [comment] 2024-02-20 17:57
@Craanky ive discovered the issue happens only when you die to a dual. Will be looking into a fix for it soon

**Comment by eloh-mrow** [comment] 2024-02-20 18:25
Fixed with [fdf5544](https://github.com/eloh-mrow/death-tracker/commit/fdf55447c4d2f9111cbb75e776e5b7ae91d9602d)

**Closed by eloh-mrow** 2024-02-20 18:25 UTC
Labels: bug
